### ISSUE TITLE
ERROR: Unable to load type [waypoints/Groups_Wp].

### ISSUE THREAD

**Issue by AmirsamanAhmadi** [halejo-as/waypoints#1]
Hello I am getting following error

ERROR: Unable to load type [waypoints/Groups_Wp].
Have you typed 'make' in [waypoints]?
[ INFO] [1616063858.160704977]: Run Wp
ERROR: Unable to load type [waypoints/Run_Wp].
Have you typed 'make' in [waypoints]?

when i try to run make in the directory i will get this 
make: *** No targets specified and no makefile found.  Stop.

could you please advice on this ?

**Comment by halejo-as** [comment]
Hello,
Don't use `make` use `catkin_make` to compile the package in your workspace

**Comment by AmirsamanAhmadi** [comment]
> Hello,
> Don't use `make` use `catkin_make` to compile the package in your workspace

Thank you for your fast reply, yes that is what I did and everything works as you showed in the video however when I try to Group run or run one point it will show me something like this error

[ INFO] [1616063784.601421491]: rviz version 1.14.4
[ INFO] [1616063784.601530917]: compiled against Qt version 5.12.8
[ INFO] [1616063784.601590821]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1616063784.724895396]: Forcing OpenGl version 0.
[ INFO] [1616063786.538000685]: Stereo is NOT SUPPORTED
[ INFO] [1616063786.538254659]: OpenGl version: 4.1 (GLSL 4.1).
[ INFO] [1616063810.148035380]: node /waypoints_server running
[ INFO] [1616063821.299568011]: Creating 1 swatches
[ INFO] [1616063841.468090231]: 
Setting waypoint p1:
  Position(3.793, -0.595, 0.000), Orientation(0.000, 0.000, 0.025, 1.000) , Angle: 0.051

[ INFO] [1616063841.498930940]: Received wp_msg
[ INFO] [1616063841.500022252]: Update waypoint server
[ INFO] [1616063848.136769356]: 
Setting waypoint p2:
  Position(7.424, 0.295, 0.000), Orientation(0.000, 0.000, 0.025, 1.000) , Angle: 0.049

[ INFO] [1616063848.171503417]: Received wp_msg
[ INFO] [1616063848.171877123]: Update waypoint server
ERROR: Unable to load type [waypoints/Groups_Wp].
Have you typed 'make' in [waypoints]?
[ INFO] [1616063858.160704977]: Run Wp
ERROR: Unable to load type [waypoints/Run_Wp].
Have you typed 'make' in [waypoints]?

**Comment by halejo-as** [comment]
Check if all the services and messages are well compiled.
`rossrv show waypoints/` Should be show you the 7 services of this package

Try to run the waypoint calling the service
`rosservice call /waypoint_server/run_wp ` (complete the args with your info, easy way tab and complete only the wp_name arg)

**Comment by AmirsamanAhmadi** [comment]
after running `rossrv show waypoints/`

I can see this message

ubuntu@ubuntu:~$ rossrv show waypoints/
Unknown srv type [waypoints/]: Cannot locate message [] in package [waypoints] w              ith paths [['/home/ubuntu/catkin_ws/src/waypoints/srv', '/home/ubuntu/catkin_ws/              devel/share/waypoints/srv']]

ubuntu@ubuntu:~$ rosservice call /waypoint_server/run_wp "wp_name: 'p1'
gr_name: 'path1'
loop: false
index: 1"
success: False

-----------

After restating the system everything works perfectly, thank you for your fast respone
