### ISSUE TITLE
Trouble running the waypoint server

### ISSUE THREAD

**Issue by aaravrav142** [halejo-as/waypoints#2]
Hi,

I installed the package on ROS Melodic successfully. I am running my own robot launch files with move base. 
After running the waypoint_server, I cannot get the toolbox on the rviz. I can add the waypoint toolbox using the '+' button on the rviz panel, however I cannot get the panel to show up. Also there is no topic published for the waypoint that I can see in the topic list. Can you help me with this? Thanks

**Comment by halejo-as** [comment]
Hi,  did you execute the node with?
```rosrun waypoints waypoints_server```
And when you add a new Panel in rviz you can see the folder with the waypoint panel?

![image](https://user-images.githubusercontent.com/59148199/116068890-09340080-a68b-11eb-80b8-412066227a2a.png)

**Comment by aaravrav142** [comment]
Yes I was running the node and can see the folder when the plus button is used on the rviz.  But the panel did not show up as indicated in the tutorial youtube video when I right click on the panel. I checked again rebooting the pc and the problem persists. What might be the problem. Is it because there is no melodic release yet?

**Comment by halejo-as** [comment]
I don't think so, I am using the server with others distros (noetic and melodic) and the package run well. 
Check your ROS environment and compile again the package, verify  the executable  (.../waypointPanel.cpp.o)  is generated and the library is linked at the end of the compilation.

**Comment by aaravrav142** [comment]
Ok I don't have access to the robot now. I will report back tomorrow. Thanks for your reply.

**Comment by aaravrav142** [comment]
Hi, 
Problem solved. It was indeed compilation problem. The executable were not generated properly. Cleaning the workspace and recompiling solved the problem. Thanks a lot for your help and this great tool.

**Comment by aaravrav142** [comment]
Hi 
Just a small query. Is there a way where the robot can be made to stay at a specific waypoint for a set period of time (few seconds) or a delay and perform some task such as rotation etc. , and then move to the next waypoint. Would be a useful addition to this package.
