### ISSUE TITLE
Start a waypoint using console

### ISSUE THREAD

**Issue by raymond6100** [halejo-as/waypoints#3]
Hello, is it there any command to start and stop waypoints from the console without using the GUI? Aside from that, it is possible to run a group without a loop.

**Comment by Darld-lwi** [comment]
@halejo-as I have same thought with @raymond6100. Further explanation, I am looking that we have pre-defined waypoints in .txt, so we can rosrun the service (single command) to feed the waypoint.txt, then the robot will auto navigate from point A to B.

**Comment by halejo-as** [comment]
Hello @raymond6100 

To start and stop and waypoint from the console you need to call the service `/waypoint_server/run_wp` check the implementation on this [line](https://github.com/halejo-as/waypoints/blob/master/src/waypointPanel.cpp#L193) .

For running a group without a loop you online have to **uncheck the box Loop** on the interface.
