### ISSUE TITLE
Unable to compile: waypoints/waypoint_msg.h file does not exist.

### ISSUE THREAD

**Issue by Gurupra5ad** [halejo-as/waypoints#4]
After running catkin_make, this error is thrown multiple times. Please help out.

![IMG-20220126-WA0010.jpg](https://user-images.githubusercontent.com/65018081/151111238-08f2b3cc-e28b-4f22-87ed-2d778dd7642f.jpg)

**Comment by halejo-as** [comment]
Remove the folder _build_ and _devel_ of your workspace and compile only the package in your workspace using `catkin_make --pkg waypoints` . Let me know if the error persists
